# coding: utf-8

"""
    Klaviyo API

    Empowering creators to own their destiny  # noqa: E501

    OpenAPI spec version: 2021.11.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EmailtemplateTemplateIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'html': 'str'
    }

    attribute_map = {
        'name': 'name',
        'html': 'html'
    }

    def __init__(self, name=None, html=None):  # noqa: E501
        """EmailtemplateTemplateIdBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._html = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if html is not None:
            self.html = html

    @property
    def name(self):
        """Gets the name of this EmailtemplateTemplateIdBody.  # noqa: E501

        The new name of the email template.  # noqa: E501

        :return: The name of this EmailtemplateTemplateIdBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EmailtemplateTemplateIdBody.

        The new name of the email template.  # noqa: E501

        :param name: The name of this EmailtemplateTemplateIdBody.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def html(self):
        """Gets the html of this EmailtemplateTemplateIdBody.  # noqa: E501

        The new HTML content for this template.  # noqa: E501

        :return: The html of this EmailtemplateTemplateIdBody.  # noqa: E501
        :rtype: str
        """
        return self._html

    @html.setter
    def html(self, html):
        """Sets the html of this EmailtemplateTemplateIdBody.

        The new HTML content for this template.  # noqa: E501

        :param html: The html of this EmailtemplateTemplateIdBody.  # noqa: E501
        :type: str
        """

        self._html = html

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EmailtemplateTemplateIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EmailtemplateTemplateIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
