# coding: utf-8

"""
    Klaviyo API

    Empowering creators to own their destiny  # noqa: E501

    OpenAPI spec version: 2021.11.26
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GlobalExclusionResponseDataData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'object': 'str',
        'email': 'str',
        'reason': 'str',
        'timestamp': 'str'
    }

    attribute_map = {
        'object': 'object',
        'email': 'email',
        'reason': 'reason',
        'timestamp': 'timestamp'
    }

    def __init__(self, object=None, email=None, reason=None, timestamp=None):  # noqa: E501
        """GlobalExclusionResponseDataData - a model defined in Swagger"""  # noqa: E501
        self._object = None
        self._email = None
        self._reason = None
        self._timestamp = None
        self.discriminator = None
        if object is not None:
            self.object = object
        if email is not None:
            self.email = email
        if reason is not None:
            self.reason = reason
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def object(self):
        """Gets the object of this GlobalExclusionResponseDataData.  # noqa: E501


        :return: The object of this GlobalExclusionResponseDataData.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this GlobalExclusionResponseDataData.


        :param object: The object of this GlobalExclusionResponseDataData.  # noqa: E501
        :type: str
        """

        self._object = object

    @property
    def email(self):
        """Gets the email of this GlobalExclusionResponseDataData.  # noqa: E501


        :return: The email of this GlobalExclusionResponseDataData.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GlobalExclusionResponseDataData.


        :param email: The email of this GlobalExclusionResponseDataData.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def reason(self):
        """Gets the reason of this GlobalExclusionResponseDataData.  # noqa: E501


        :return: The reason of this GlobalExclusionResponseDataData.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this GlobalExclusionResponseDataData.


        :param reason: The reason of this GlobalExclusionResponseDataData.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def timestamp(self):
        """Gets the timestamp of this GlobalExclusionResponseDataData.  # noqa: E501


        :return: The timestamp of this GlobalExclusionResponseDataData.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this GlobalExclusionResponseDataData.


        :param timestamp: The timestamp of this GlobalExclusionResponseDataData.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalExclusionResponseDataData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalExclusionResponseDataData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
